.tgitconfig, LICENSE
=> Update LICENSE, add .tgitconfig

docker/docker-compose.yml, docker/manage, identity-controller/package.json, wa-admin/package.json, wa-public/package.json
This PR fixes the issues described in #8
=> Fix contanier start-up

docker/docker-compose.yml, docker/keycloak/config/realm-export.json, wa-admin/angular.json, wa-admin/package-lock.json, wa-admin/package.json, wa-admin/src/app/app-routing.module.ts, wa-admin/src/app/app.module.ts, wa-admin/src/app/guards/can-activate.guard.ts, wa-admin/src/assets/data/appConfig.json, wa-admin/src/proxy.conf.json, wa-public/angular.json, wa-public/package.json, wa-public/src/proxy.conf.json
Add Keycloak authentication support to the `wa-admin` app.
=> Keycloak integration

docker/docker-compose.yml, identity-controller/package.json
=> Tweaks to docker-compose for identity-controller service

wa-admin/src/app/pages/home/components/add-user-preview/add-user-preview.component.ts, wa-admin/src/app/pages/home/components/add-user/add-user.component.ts, wa-admin/src/app/pages/home/components/manage-users/manage-users.component.ts, wa-admin/src/app/pages/home/components/user-list-item/user-list-item.component.ts, wa-admin/src/app/pages/home/components/view/view.component.ts, wa-admin/src/app/pages/home/home.page.ts, wa-admin/src/app/services/action.service.ts, wa-admin/src/app/shared/components/card-toolbar/card-toolbar.component.ts, wa-admin/src/app/shared/interfaces/invitation-record.interface.ts, wa-admin/src/styles.scss
- invited tab on home:
- pending > sent x
- changed the confirmed tab to used (optionally flatten menu now and use filters)
- change the heading from confirmed to used on home page
- change the confirmed > to issued / logged in
- pending to sent x
- consumed to logged in x
- active to issued x
- removed state controls for disabling
- corrected labels
- removed link
- added first & last
- consumed to logged in x
- active to issued x
- flattened button for jursdiction
- added defaults for jur. & method
- added option fname lname
- added require stars
- changed the confirmed tab to used (optionally flatten menu now and use filters)
=> Admin ui feedback

docker/keycloak/config/realm-export.json, docker/manage
=> Add GitHub as Keycloak IDP

docker/keycloak/config/realm-export.json
=> Fix realm-export.json

wa-admin/src/app/pages/home/components/add-user/add-user.component.ts, wa-admin/src/app/services/action.service.ts
corrections for the label on add user component and corrected the display of the expiry date on add user and resend invitations
Signed-off-by: Sean Hamilton <hamiltonsean6@icloud.com>
=> Demo corrections

.gitignore, docker/manage
=> Improve integration of custom Keycloak configuration with docker environment.

docker/keycloak/config/realm-export.json, wa-public/src/app/app-routing.module.ts, wa-public/src/app/app.module.ts, wa-public/src/app/components/card-list-item/card-list-item.component.scss, wa-public/src/app/components/card-list-item/card-list-item.component.ts, wa-public/src/app/components/credential-issuance/credential-issuance.component.ts, wa-public/src/app/components/input/input.component.ts, wa-public/src/app/components/issue-preview/issue-preview.component.scss, wa-public/src/app/components/issue-preview/issue-preview.component.ts, wa-public/src/app/pages/success/success.component.scss, wa-public/src/app/pages/success/success.component.ts, wa-public/src/app/pages/track/track.component.spec.ts, wa-public/src/app/pages/track/track.component.ts
updates from feedback with Peter and incorporated the 'pizza tracker'  for issuing credentials
Signed-off-by: Sean Hamilton <hamiltonsean6@icloud.com>
=> public front-end finish

docker/wa-admin/Dockerfile, docker/wa-admin/Dockerfile.dockerprod, docker/wa-admin/config/Caddyfile, docker/wa-public/Dockerfile, docker/wa-public/Dockerfile.dockerprod, docker/wa-public/config/Caddyfile, wa-admin/src/environments/environment.prod.ts, wa-public/src/environments/environment.prod.ts
=> Tweaks to production deployment mode.

README.md
Signed-off-by: Stephen Curran <swcurran@gmail.com>
=> Fixing bad link to von-network

identity-controller/src/app/models/database/database.model.ts
=> Use environment variable for database name

identity-controller/src/app/models/database/database.model.ts
=> Add default (empty) value to DB_NAME

identity-controller/src/app/services/email.service.ts
=> Set TLS to true when running in production mode

identity-controller/src/app/services/email.service.ts
=> Fix SMTP server call

openshift/templates/identity-kit-agent/identity-kit-agent-deploy.yaml
=> Rename agent wallet

docker/docker-compose.yml, identity-controller/src/app/admin/webhooks/webhooks.controller.ts, identity-controller/src/app/services/email.service.ts, identity-controller/src/core/agent-controller/modules/issue/issue.model.ts
stopping the credential status for the pizza tracker at request state
Signed-off-by: Sean Hamilton <hamiltonsean6@icloud.com>
=> Fix for stopping the Credential Tracker before streetcred accepts it

docs/GettingApp.md
Signed-off-by: Stephen Curran <swcurran@gmail.com>
=> Instructions for setting up the Streetcred app

docs/GettingApp.md
Signed-off-by: Stephen Curran <swcurran@gmail.com>
=> Typo in the title. Really?

identity-controller/src/app/services/invitation_email.ts
Signed-off-by: Stephen Curran <swcurran@gmail.com>
=> New link for instructions to download and setup Streetcred app

identity-controller/src/app/admin/invitation/invitation.controller.ts, identity-controller/src/app/services/email.service.ts, wa-public/src/app/app.module.ts, wa-public/src/app/pages/success/success.component.scss, wa-public/src/app/pages/success/success.component.ts
- new Datepicker that better supports desktop use cases.
- link now correctly appears in a renewal email.
=> Frontend public changes for issue: https://github.com/bcgov/identity-kit-poc/issues/64

identity-controller/src/app/admin/invitation/invitation.controller.ts, identity-controller/src/app/admin/invitation/invitation.service.ts, identity-controller/src/app/services/email.service.ts, wa-public/package-lock.json, wa-public/package.json, wa-public/prettierrc.json, wa-public/src/app/app-routing.module.ts, wa-public/src/app/app.module.ts, wa-public/src/app/components/accept-disclaimer/accept-disclaimer.component.scss, wa-public/src/app/components/accept-disclaimer/accept-disclaimer.component.ts, wa-public/src/app/components/request-token/request-token.component.scss, wa-public/src/app/components/request-token/request-token.component.ts, wa-public/src/app/guards/request-token.guard.spec.ts, wa-public/src/app/guards/request-token.guard.ts, wa-public/src/app/guards/valid-invite.guard.ts, wa-public/src/app/pages/success/success.component.scss, wa-public/src/app/pages/success/success.component.ts, wa-public/src/app/services/action.service.ts, wa-public/src/app/services/state.service.ts
Completed adjustments so that the re-direction occurs properly within the public app (validate link ID > isValid ? go to login page : go to the request new token route || to the blank route)
- refactored redirect code in controller to properly support the front-end redirect scheme.
- Added ignore urls to the bearerExludedUrl settings in app.module for keycloak.
- Re-factored guard to correctly return proper route navigations.
- Added the request token sub-page
- Added email that is sent to Peter // admin (environment variable process.env.ADMIN_EMAIL) when new token is requested. Current verbiage: sean.hamilton@quartech.com has requested a new email token. They were signed up using the address: test@test.com.
note: the user only receives feedback the token has been requested. They're not …
=> Frontend/validate: Bug-Fixes and Feature Changes for Issue: https://github.com/bcgov/identity-kit-poc/issues/64

identity-controller/src/app/admin/invitation/invitation.controller.ts, wa-admin/src/app/pages/home/home.page.scss, wa-admin/src/app/pages/home/home.page.ts, wa-public/src/app/components/accept-disclaimer/accept-disclaimer.component.scss, wa-public/src/app/components/card-list-item/card-list-item.component.scss, wa-public/src/app/components/request-token/request-token.component.scss, wa-public/src/app/pages/success/success.component.ts
Corrected a problem with the deeplink url for opening on streetcred.
Removed some font-weight settings.
Corrected the admin card toolbar from dropping overtop of the main toolbar.
Added margins bottom to the admin page so that bottom list items are no longer partially obstructed on desktop.
=> Minor view corrections and polish for mobile

wa-public/src/app/components/credential-issuance/credential-issuance.component.ts
Missed a value in the redirect uri. After completing the flow the user should be redirected to: https://identity-kit.pathfinder.gov.bc.ca/completed
Signed-off-by: seanadipose <hamiltonsean6@icloud.com>
=> Correct re-direct URI for logging out of a completed credential issuance.

wa-public/src/app/pages/completed/completed.component.ts
Page now says:
Congratulations on issuing a credential!
You have completed the Identity Kit Proof of Concept(POC).
To try out your new verified person credential please go to this demo site
Signed-off-by: seanadipose <hamiltonsean6@icloud.com>
=> updated verbiage on the completed page

wa-public/src/app/pages/success/success.component.ts
Corrected name validation to now be min-length of 1 for surname and given name.
Signed-off-by: seanadipose <hamiltonsean6@icloud.com>
=> Corrected name validation to now be min-length of 1 for surname and given name

openshift/templates/identity-kit-agent/identity-kit-agent-deploy.prod.param
=> Update agent label

identity-controller/src/core/agent-controller/modules/connection/connection.service.ts, wa-public/package-lock.json, wa-public/src/app/app.module.ts, wa-public/src/app/components/credential-issuance/credential-issuance.component.ts, wa-public/src/app/models/cp-request.spec.ts, wa-public/src/app/models/cp-request.ts, wa-public/src/app/pages/success/success.component.scss, wa-public/src/app/pages/success/success.component.ts, wa-public/src/app/services/action.service.ts, wa-public/src/app/services/typeahead.service.spec.ts, wa-public/src/app/services/typeahead.service.ts
Completed adding typeahead on the public issuing form.
Also adjusted polling to be 1s.
=> Add Typeahead to the address field on the public issuing form

docker/docker-compose.yml, identity-controller/src/app/admin/issues/issue.controller.ts, identity-controller/src/app/admin/issues/issue.service.ts, identity-controller/src/core/agent-controller/modules/issue/issue.model.ts, identity-controller/src/core/interfaces/issue-credential.interface.ts, wa-public/src/app/pages/success/success.component.ts
changes to data submission:
credential_definition id to cred_def_id
auto_issue = false
Signed-off-by: seanadipose <hamiltonsean6@icloud.com>
=> Updates to fix issuing on 0.40 agent

identity-controller/src/app/services/invitation_email.ts, wa-public/src/app/pages/completed/completed.component.ts
=> Updated DARS Audio app link

jenkins/config.groovy
=> Updated jenkinsfile

README.md, docker/docker-compose.yml, docker/manage, identity-controller/package.json, wa-admin/package.json, wa-public/package.json, wa-public/src/app/app-routing.module.ts, wa-public/src/app/app.module.ts
Small tweak to the development mode, that requires a slight update of the instructions so double checking this works 😉
=> Tweaks to dev mode

identity-controller/src/app/services/email.service.ts
=> Fix syntax error in controller code

docker/wa-admin/config/config.json, identity-controller/src/app/admin/admin.ts, wa-admin/src/app/pages/home/components/add-user/add-user.component.ts, wa-admin/src/app/services/action.service.ts, wa-admin/src/assets/config/config.json, wa-admin/src/assets/config/form-template.ts, wa-public/src/app/guards/valid-invite.guard.ts
Use configuration file to define user invite form fields.
=> Parametrize admin registration fields

wa-public/src/app/pages/success/success.component.ts
=> Tweaks to handle agent connection state properly

wa-public/package-lock.json, wa-public/package.json, wa-public/src/app/components/accept-disclaimer/accept-disclaimer.component.ts, wa-public/src/app/components/credential-issuance/credential-issuance.component.ts, wa-public/src/app/pages/success/success.component.ts, wa-public/src/app/pages/track/track.component.ts, wa-public/src/app/services/action.service.ts, wa-public/src/app/services/state.service.ts
Additional OIDC claims integrated in flow.
=> Integrate additional OIDC claims

wa-public/src/app/components/request-token/request-token.component.ts, wa-public/src/app/services/action.service.ts
=> Tweaks to request-token.component.ts

docker/agent/Dockerfile, docker/docker-compose.yml
Signed-off-by: Wade Barnes <wade.barnes@shaw.ca>
=> Update bcgovimages/aries-cloudagent image version

docker/manage
=> Use random did for issuer

identity-controller/src/app/admin/invitation/invitation.service.ts
=> Bugfix for re-issuing credentials using the same link

issuer-web/src/router/index.ts, issuer-web/src/store/modules/connection/actions.ts, issuer-web/src/views/Connect.vue, issuer-web/src/views/IssueCredential.vue
Using Axios interceptors to clean up a bit API polling and simplify handling timeouts (they are not necessary anymore).
=> Use Axios interceptor when polling API

issuer-web/src/components/DataCollection.vue, issuer-web/src/components/Footer.vue, issuer-web/src/components/Header.vue, issuer-web/src/main.ts, issuer-web/src/models/appConfig.ts, issuer-web/src/models/storeState.ts, issuer-web/src/services/config/index.ts, issuer-web/src/store/index.ts, issuer-web/src/store/modules/configuration/actions.ts, issuer-web/src/store/modules/configuration/configuration.ts, issuer-web/src/store/modules/configuration/getters.ts, issuer-web/src/store/modules/configuration/mutations.ts, issuer-web/src/store/modules/connection/actions.ts, issuer-web/src/store/modules/invitation/actions.ts, issuer-web/src/views/IssueCredential.vue
=> Cache configuration(s) to avoid making multiple requests for the same file

docker/issuer-web/config/config.json, issuer-web/public/config/config.json, issuer-web/src/models/appConfig.ts, issuer-web/src/router/guards/valid-token.ts
=> Add unprotected access option to issuer-web

issuer-web/public/config/custom-scripts.js, issuer-web/public/index.html, issuer-web/src/components/DataCollection.vue
=> Add custom JS support, including custom functions for SurveyJS widget.

identity-controller/src/app/admin/issues/issue.controller.ts, issuer-web/src/views/IssueCredential.vue
=> Handle issuing credential without invite

issuer-web/src/views/Connect.vue
=> Increse QR code size

identity-controller/src/app/admin/issues/issue.service.ts
=> Fix bug when issuing credential for existing schema id

issuer-web/src/store/modules/connection/actions.ts
Prevent the interceptor listening for the "connection ready" event to break navigating away from the page when clicking the back button.
=> Fix back navigation on Connect page

identity-controller/src/app/admin/issues/issue.service.ts
=> Fix schema not found error

jenkins/config.groovy
=> Fix build pipeline

openshift/templates/api/config/bc/invite-email.html
=> Updated invite-email.html for bc profile

docker/agent/Dockerfile, docker/docker-compose.yml
=> Update aries-cloudagent image to 0.5.2

docs/GettingApp.md
Signed-off-by: Kevin Dinh <kevin.dinh@main-incubator.com>
=> Included Lissi Wallet in GettingApp.md

api/src/logger.ts, docker/docker-compose.yml, openshift/templates/api/api-deploy.bc.param, openshift/templates/api/api-deploy.bc.prod.param, openshift/templates/api/api-deploy.bc.test.param, openshift/templates/api/api-deploy.json
I have NOT yet deployed the changes to OpenShift: the environment variable is NOT required for the deployments to work, I will update them if/when we need to update something more significant (or I need to debug).
=> Configurable log level for api

openshift/templates/agent/agent-deploy.bc.param, openshift/templates/agent/agent-deploy.bc.prod.param, openshift/templates/agent/agent-deploy.bc.test.param, openshift/templates/agent/agent-deploy.yaml
=> Update agent deployment configuration to account for new tails file location.

openshift/templates/agent/agent-deploy.bc.param, openshift/templates/agent/agent-deploy.bc.prod.param, openshift/templates/agent/agent-deploy.bc.test.param, openshift/templates/agent/agent-deploy.yaml
=> Restored user-configurable TAILS_FILES_DIR

api/package-lock.json, api/package.json, api/src/services/issuer-invite/issuer-invite.hooks.ts
=> Bump api dependencies, fix revocation flow in api.

issuer-admin/package-lock.json, issuer-admin/package.json, issuer-web/package-lock.json, issuer-web/package.json, issuer-web/src/views/IssueCredential.vue
Correctly sign-out user after successful credential issuance flow.
Bump dependencies for issuer-admin, issuer-web.
=> Correctly sign-out user after successful credential issuance flow.

api/package-lock.json, api/package.json
=> Bump dependencies for api

openshift/templates/issuer-admin/config/bc/prod/config.json, openshift/templates/issuer-admin/config/bc/test/config.json, openshift/templates/issuer-web/config/bc/prod/config.json, openshift/templates/issuer-web/config/bc/test/config.json
Updted configurations to target new OIDC service.
Changes were deployed and tested in openshift for both TEST and PROD.
=> Update oidc authentication configuration for admin, issuer webapps.

docker/agent/Dockerfile, docker/docker-compose.yml
=> Apdate aca-py to 0.5.5

docker/agent/Dockerfile, docker/docker-compose.yml
=> Update aca-py to 0.5.6

openshift/templates/issuer-web/config/bc/prod/config.json, openshift/templates/issuer-web/config/bc/test/config.json
=> Update post-issuance links for BC deployment.

openshift/templates/api/config/bc/prod/schemas.json, openshift/templates/api/config/bc/test/schemas.json
=> Update schema settings for BCGov issuer

api/src/utils/hooks.ts
=> Clean up hooks code

docs/ConfiguringIssuerKit.md
=> Fix to ConfiguringIssuerKit.md

issuer-web/package-lock.json, issuer-web/package.json, issuer-web/src/models/appConfig.ts, issuer-web/src/router/guards/pres-req.ts, issuer-web/src/router/index.ts, issuer-web/src/utils/index.ts
@esune please have a look and approve
=> added beforeEnter gaurd

docker/agent/Dockerfile, openshift/templates/agent/agent-deploy.yaml
=> Upgrade ACA-Py to 0.6.0

api/package-lock.json, api/package.json, issuer-admin/package-lock.json, issuer-admin/package.json, issuer-web/package-lock.json, issuer-web/package.json
=> Updated dependencies

issuer-admin/package-lock.json, issuer-admin/package.json, issuer-web/package-lock.json, issuer-web/package.json
=> Fix build issues due to a missing peer dependency of survey-vue

api/src/mongodb.ts
updated db connection params
Signed-off-by: wadeking98 <wkingnumber2@gmail.com>
=> updated feature-health-check settings

README.md, docker/docker-compose.yml, docker/manage, issuer-admin/public/config/config.json, issuer-web/public/config/config.json
... (5050 instead of 5000), and update to latest aca-py version
=> Update to use Mac-friendly port

issuer-web/src/store/modules/invitation/actions.ts
Fixed validation token in frontend treating an invalid token as valid. 
Resolves: https://github.com/bcgov/trust-over-ip-configurations/issues/91
Signed-off-by: wadeking98 <wkingnumber2@gmail.com>
=> fixed token validation bug

issuer-admin/src/styles.scss, issuer-web/src/styles.scss
update surveyjs css styling as mentioned in this toip issue:
Resolves: https://github.com/bcgov/trust-over-ip-configurations/issues/98
Signed-off-by: wadeking98 <wkingnumber2@gmail.com>
=> updated surveyjs css endpoint

docker/issuer-web/config/web/config.json, issuer-web/public/config/config.json, issuer-web/src/models/appConfig.ts, issuer-web/src/views/Connect.vue
Added deeplink prefix to config file so the demo can support custom wallets
Signed-off-by: wadeking98 <wkingnumber2@gmail.com>
=> Added deeplink prefix to config for demos with custom wallets

.github/stale.yml
=> Add probot-stale configuration

docker/docker-compose.yml, docker/keycloak/config/realm-export.json, docker/manage
=> Upgrade keycloak, postgres, aca-py images.

README.md, docker/docker-compose.yml, docker/manage
Adding ACAPY_WALLET_SEED environment variable on the manage script and it's usage on the docker-compose Issuer Kit Agent section.
Updating README file with the introduced ACAPY_WALLET_SEED environment variable.
=> Wallet Seed environment variable consistency

.github/stale.yml
Replaced the deprecated `probot/stale` with the new GHA
=> Update stale bot action and configuration.

.github/stale.yml
- Ensure dependency related PRs are exempt.
=> Update Stale Action
